name: e2e tests
on:
  pull_request

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    env:
      node-version: 12
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.node-version }}'
          check-latest: true

      - name: Restore NPM cache if exist
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-${{ env.node-version }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 310
          command: npm run currents
          