name: e2e tests
on:
  pull_request

  e2e_tests:
    runs-on: ubuntu-latest
    env:
      node-version: 12
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 310
          command: npm run currents
          